spring:
  application:
    name: USER-SERVICES
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/validation
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
        type: trace
    generate-ddl: true

